<a href="https://colab.research.google.com/github/Arnav8055singh/ML-DL-projects/blob/main/Credit_Card_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Kaggle DataSet

In [1]:
import kagglehub


path = kagglehub.dataset_download("mlg-ulb/creditcardfraud")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/mlg-ulb/creditcardfraud?dataset_version_number=3...

100%|██████████| 66.0M/66.0M [00:00<00:00, 84.5MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/mlg-ulb/creditcardfraud/versions/3

Import The Dependecies

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [4]:
#load the dataset to a Pandas Dataframe

credit_card_data = pd.read_csv('/content/creditcard.csv')

In [6]:
#first 5 rows of the dataset

credit_card_data.head()

   Time        V1        V2        V3        V4  ...       V26       V27       V28  Amount  Class
0     0 -1.359807 -0.072781  2.536347  1.378155  ... -0.189115  0.133558 -0.021053  149.62    0.0
1     0  1.191857  0.266151  0.166480  0.448154  ...  0.125895 -0.008983  0.014724    2.69    0.0
2     1 -1.358354 -1.340163  1.773209  0.379780  ... -0.139097 -0.055353 -0.059752  378.66    0.0
3     1 -0.966272 -0.185226  1.792993 -0.863291  ... -0.221929  0.062723  0.061458  123.50    0.0
4     2 -1.158233  0.877737  1.548718  0.403034  ...  0.502292  0.219422  0.215153   69.99    0.0

[5 rows x 31 columns]

In [7]:
credit_card_data.tail()

        Time        V1        V2        V3        V4  ...       V26       V27       V28  Amount  Class
37717  39076  1.117749 -1.544665 -0.145357 -1.307482  ... -0.460844 -0.029143  0.029028  183.19    0.0
37718  39076  0.758729 -0.483875  0.125488  1.449159  ... -0.304812 -0.033008  0.063331  250.00    0.0
37719  39076 -0.474907  0.835804  0.075878 -1.251283  ...  0.084198  0.310936  0.170342    1.49    0.0
37720  39077 -2.682780 -2.028562  1.745223 -1.157952  ... -0.209058  0.256991 -0.585781  102.00    0.0
37721  39077  1.106292 -0.525727  0.926440  0.817696  ...       NaN       NaN       NaN     NaN    NaN

[5 rows x 31 columns]

In [8]:
#dataset information

credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37722 entries, 0 to 37721
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    37722 non-null  int64
 1   V1      37722 non-null  float64
 2   V2      37722 non-null  float64
 3   V3      37722 non-null  float64
 4   V4      37722 non-null  float64
 5   V5      37722 non-null  float64
 6   V6      37722 non-null  float64
 7   V7      37721 non-null  float64
 8   V8      37721 non-null  float64
 9   V9      37721 non-null  float64
 10  V10     37721 non-null  float64
 11  V11     37721 non-null  float64
 12  V12     37721 non-null  float64
 13  V13     37721 non-null  float64
 14  V14     37721 non-null  float64
 15  V15     37721 non-null  float64
 16  V16     37721 non-null  float64
 17  V17     37721 non-null  float64
 18  V18     37721 non-null  float64
 19  V19     37721 non-null  float64
 20  V20     37721 non-null  float64
 21  V21     37721 non-null  float64
 22  V22     37721 non-null  float64
 23  V23     37721 non-null  float64
 24  V24     37721 non-null  float64
 25  V25     37721 non-null  float64
 26  V26     37721 non-null  float64
 27  V27     37721 non-null  float64
 28  V28     37721 non-null  float64
 29  Amount  37721 non-null  float64
 30  Class   37721 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 8.9 MB

In [9]:
#checking the missing values in each column

credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [14]:
#Distribution of legit Transactions and fraudulent Transactions
credit_card_data['Class'].value_counts()

Class
0.0    37618
1.0      103
Name: count, dtype: int64

The DataSet is Highly Imbalanced
0-> Normal Transactions
1-> Fraudelent Transactions

In [18]:
#Separating the Data For Analaysis

legit = credit_card_data [credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [19]:
print(legit.shape)
print(fraud.shape)

(37618, 31)
(103, 31)

In [20]:
#Statistical Measures for the data

legit.Amount.describe()

count    37618.000000
mean        86.017411
std        232.957939
min          0.000000
25%          7.300000
50%         22.880000
75%         77.675000
max       7879.420000
Name: Amount, dtype: float64

In [21]:
fraud.Amount.describe()

count     103.000000
mean       90.471165
std       247.173335
min         0.000000
25%         1.000000
50%         3.760000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [22]:
#compare the values for both Transactions

credit_card_data.groupby('Class').mean()

               Time        V1        V2         V3  ...       V26       V27       V28     Amount
Class                                               ...
0.0    24778.212797 -0.186787  0.044196   0.749331  ...  0.021382  0.007030  0.003658  86.017411
1.0    20498.291262 -7.762676  5.838647 -10.957218  ...  0.180390  0.822304  0.102481  90.471165

[2 rows x 30 columns]

Under Sampling



Number of Fraudelent Transactions --> 103

In [25]:
legit_sample = legit.sample(n=103)

Cocatenating two DataFrames

In [26]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [27]:
new_dataset.tail()

        Time        V1        V2        V3        V4  ...       V26       V27       V28  Amount  Class
30442  35926 -3.896583  4.518355 -4.454027  5.547453  ...  0.412191  0.635789  0.501050    4.56    1.0
30473  35942 -4.194074  4.382897 -5.118363  4.455230  ... -0.131687  0.473934  0.473757   14.46    1.0
30496  35953 -4.844372  5.649439 -6.730396  5.252842  ... -0.270328  0.210214  0.391855  111.70    1.0
31002  36170 -5.685013  5.776516 -7.064977  5.902715  ... -0.049447  0.303445  0.219380  111.70    1.0
33276  37167 -7.923891 -5.198360 -3.000024  4.420666  ...  0.520508  1.937421 -1.552593   12.31    1.0

[5 rows x 31 columns]

In [28]:
new_dataset['Class'].value_counts()

Class
0.0    103
1.0    103
Name: count, dtype: int64

In [29]:
new_dataset.groupby('Class').mean()

               Time        V1        V2         V3  ...       V26       V27       V28      Amount
Class                                               ...
0.0    22938.029126 -0.640504  0.198686   0.785019  ...  0.014012  0.059001 -0.004726  120.049223
1.0    20498.291262 -7.762676  5.838647 -10.957218  ...  0.180390  0.822304  0.102481   90.471165

[2 rows x 30 columns]

Spliting the Data into Features And Targets

In [32]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [33]:
print(X)

        Time        V1        V2        V3  ...       V26       V27       V28  Amount
11354  19786 -1.820687  2.553855 -3.600587  ... -0.448251  0.152396 -0.201687   89.99
1103     856 -0.916706  0.749862  2.067662  ... -0.469512 -0.127948  0.162297   23.90
3488    2984  0.788630 -2.175959 -0.318479  ... -0.103503 -0.057791  0.075507  398.00
10821  18458  1.185175 -0.378995  0.995367  ... -0.693868  0.075936  0.025583   11.85
22703  32391 -0.868260  0.932589  0.571916  ... -0.082223  0.461912  0.222029   22.00
...      ...       ...       ...       ...  ...       ...       ...       ...     ...
30442  35926 -3.896583  4.518355 -4.454027  ...  0.412191  0.635789  0.501050    4.56
30473  35942 -4.194074  4.382897 -5.118363  ... -0.131687  0.473934  0.473757   14.46
30496  35953 -4.844372  5.649439 -6.730396  ... -0.270328  0.210214  0.391855  111.70
31002  36170 -5.685013  5.776516 -7.064977  ... -0.049447  0.303445  0.219380  111.70
33276  37167 -7.923891 -5.198360 -3.000024  ...  0.520508  1.937421 -1.552593   12.31

[206 rows x 30 columns]

In [34]:
print(Y)

11354    0.0
1103     0.0
3488     0.0
10821    0.0
22703    0.0
        ...
30442    1.0
30473    1.0
30496    1.0
31002    1.0
33276    1.0
Name: Class, Length: 206, dtype: float64

Split the Data into Training data and the testing data

In [36]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [37]:
print(X.shape, X_train.shape, X_test.shape)

(206, 30) (164, 30) (42, 30)

Model Training -> Logistic Regression

In [38]:
model = LogisticRegression()

In [ ]:
#Training the logistic Regression Model with Training Data

In [39]:
model.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Evaluation of Model with Accuracy Model

In [40]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [41]:
print('Accuracy on training data : ', training_data_accuracy)

Accuracy on training data :  0.975609756097561

Getting the Accuracy of 97.5%

In [42]:
#Accuracy on Test data

X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [43]:
print('Accuracy score on Test Data: ', test_data_accuracy)

Accuracy score on Test Data:  0.9285714285714286